- name: Ensure rsync is installed
  apt:
    name: rsync
    state: present
    update_cache: yes

- name: Ensure backup directory exists
  file:
    path: /mnt/var-backup
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Generate timestamp
  command: date +%Y-%m-%d_%H-%M-%S
  register: backup_timestamp
  changed_when: false

- name: Create timestamped backup of /var
  command: rsync -avx /var/ /mnt/var-backup/{{ backup_timestamp.stdout }}/
  
  #  -a (archive mode) → Preserves file permissions, symlinks, timestamps, etc.
  #  -v (verbose mode) → Shows detailed output during the copy process.
  #  -x (one-file system) → Prevents crossing filesystem boundaries (e.g., skipping mounted directories like /proc and /sys).

- name: Mount new /var
  mount:
    path: /var
    src: /dev/vg_var/lv_var
    fstype: ext4
    opts: defaults
    state: mounted

- name: Restore backup to new /var
  command: rsync -av /mnt/var-backup/{{ backup_timestamp.stdout }}/ /var/

- name: Update /etc/fstab
  template:
    src: fstab.j2
    dest: /etc/fstab
    owner: root
    group: root
    mode: '0644'
