---
- name: Backup existing /var
  command: rsync -avx /var/ /mnt/var-backup/

- name: Mount new /var
  mount:
    path: /var
    src: /dev/vg_var/lv_var
    fstype: ext4
    opts: defaults
    state: mounted

- name: Update /etc/fstab
  template:
    src: fstab.j2
    dest: /etc/fstab
    owner: root
    group: root
    mode: '0644'
