---
- name: Ensure backup directory exists
  file:
    path: /mnt/var-backup
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Create timestamped backup of /var
  command: >
    rsync -avx /var/ /mnt/var-backup/$(date +%Y-%m-%d_%H-%M-%S)/
  args:
    creates: "/mnt/var-backup/$(date +%Y-%m-%d_%H-%M-%S)/"

- name: Mount new /var
  mount:
    path: /var
    src: /dev/vg_var/lv_var
    fstype: ext4
    opts: defaults
    state: mounted

- name: Update /etc/fstab
  template:
    src: fstab.j2
    dest: /etc/fstab
    owner: root
    group: root
    mode: '0644'
